<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="Stripe.net" Version="50.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gaming-Shop.CartManagement\Gaming-Shop.CartManagement.csproj" />
  </ItemGroup>

</Project>
